# Generated by Django 4.2.1 on 2023-05-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('W', 'Working'), ('F', 'finished')], default='N', max_length=1),
        ),
    ]
