# Generated by Django 4.2.1 on 2023-05-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='hello',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
