# Generated by Django 4.2.1 on 2023-05-29 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productsinfo_comments_remove_baskets_product_and_more'),
        ('users', '0003_remove_users_orders'),
        ('orders', '0003_orders_hello'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='product',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='product',
            field=models.ManyToManyField(to='products.products'),
        ),
    ]
