# Generated by Django 4.2.1 on 2023-05-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_user_remove_orderinfo_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='hello',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('W', 'Working'), ('F', 'Finished')], default='N', max_length=1),
        ),
    ]
