# Generated by Django 4.2.1 on 2023-05-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinfo',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='baskets',
            name='product',
        ),
        migrations.AddField(
            model_name='baskets',
            name='product',
            field=models.ManyToManyField(to='products.products'),
        ),
    ]
