# Generated by Django 4.2.1 on 2023-05-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_productsinfo_productinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='products_info',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='products_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
            preserve_default=False,
        ),
    ]
