# Generated by Django 4.2.1 on 2023-06-09 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women')], max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('order_count', models.IntegerField(blank=True, default=0)),
                ('email', models.EmailField(max_length=254)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.baskets')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
