# Generated by Django 4.2.1 on 2023-06-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_baskets_product'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='clients',
            name='patronymic',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='basket',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.baskets'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Men'), ('W', 'Women')], max_length=1, null=True),
        ),
    ]
