# Generated by Django 4.2.1 on 2023-05-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Baskets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
                ('status', models.IntegerField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fashion.addresses')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('order_count', models.IntegerField()),
                ('is_man', models.BooleanField()),
                ('email', models.CharField(max_length=255)),
                ('basket_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fashion.baskets')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.comments')),
                ('orders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.orders')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('seo_text', models.TextField()),
                ('comments_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.comments')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField(default=5)),
                ('favorite_count', models.IntegerField(default=0)),
                ('sale', models.IntegerField(default=0)),
                ('for_man', models.BooleanField()),
                ('type', models.CharField(max_length=255)),
                ('visible', models.BooleanField()),
                ('products_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.productsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price_per_quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fashion.products')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.users')),
            ],
        ),
        migrations.AddField(
            model_name='baskets',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashion.products'),
        ),
    ]
