# Generated by Django 4.2.1 on 2023-05-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0003_rename_product_id_baskets_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='county',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.RemoveField(
            model_name='products',
            name='for_man',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_man',
        ),
        migrations.AlterField(
            model_name='baskets',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fashion.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='favorite_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='products',
            name='sale',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='productsinfo',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fashion.comments'),
        ),
        migrations.AlterField(
            model_name='users',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fashion.comments'),
        ),
        migrations.AlterField(
            model_name='users',
            name='order_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fashion.orders'),
        ),
    ]
