# Generated by Django 4.2.1 on 2023-05-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0004_rename_county_addresses_country_remove_orders_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('W', 'Working')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
