# Generated by Django 4.2.1 on 2023-05-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0005_orders_status_products_gender_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('H', 'Головные уборы'), ('UB', 'Верх тела'), ('LB', 'Низ тела'), ('LG', 'Ноги'), ('UW', 'Белье')], max_length=2),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
