# Generated by Django 4.2.1 on 2023-05-26 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('fashion', '0006_alter_products_type_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.addresses'),
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
