# Generated by Django 4.2.1 on 2023-05-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
