# Generated by Django 4.2.1 on 2023-05-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productsinfo_comments_remove_baskets_product_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='comment',
        ),
        migrations.AlterField(
            model_name='users',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.baskets'),
        ),
    ]
